from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from pptx import Presentation


def find_layout_by_name(prs: Presentation, keyword: str):
    for layout in prs.slide_layouts:
        if keyword in layout.name:
            return layout
    raise ValueError(f"Layout not found with keyword: {keyword}")


def clear_all_slides(prs: Presentation) -> None:
    sld_id_lst = prs.slides._sldIdLst
    for sld_id in list(sld_id_lst):
        rel_id = sld_id.rId
        prs.part.drop_rel(rel_id)
        sld_id_lst.remove(sld_id)


def fill_placeholders(slide, texts: list[str]) -> None:
    placeholders = []
    for shape in slide.shapes:
        if not getattr(shape, "is_placeholder", False):
            continue
        if not getattr(shape, "has_text_frame", False):
            continue
        idx = shape.placeholder_format.idx
        placeholders.append((idx, shape))
    placeholders.sort(key=lambda item: item[0])
    for i, text in enumerate(texts):
        if i >= len(placeholders):
            break
        placeholders[i][1].text = text


def build_knowledge_base(template_path: Path, kb_path: Path) -> dict[str, Any]:
    prs = Presentation(str(template_path))
    kb = {
        "template_file": template_path.name,
        "slide_size_emu": {"width": prs.slide_width, "height": prs.slide_height},
        "slide_count": len(prs.slides),
        "layout_count": len(prs.slide_layouts),
        "semantic_layout_map": {
            "cover": "封面_Cover",
            "toc": "目录页_Content",
            "section": "章节页_Section page",
            "sub_section": "副章节页_Sub section page",
            "content": "标准内容页_Standard page",
            "content_with_subtitle": "标准内容页（小标题）_Standard page with subtitle",
            "end": "封底_End page",
        },
        "thanks_page_reference": {
            "expected_layout": "封底_End page",
            "expected_text": "Thanks.",
            "template_slide_index_0_based": 55,
        },
    }
    kb_path.parent.mkdir(parents=True, exist_ok=True)
    kb_path.write_text(json.dumps(kb, ensure_ascii=False, indent=2), encoding="utf-8")
    return kb


def generate_demo(template_path: Path, output_path: Path, kb: dict[str, Any]) -> None:
    prs = Presentation(str(template_path))
    clear_all_slides(prs)

    m = kb["semantic_layout_map"]
    cover = prs.slides.add_slide(find_layout_by_name(prs, m["cover"]))
    fill_placeholders(cover, ["cc Demo Deck", "Generated by ppt-template-builder skill"])

    toc = prs.slides.add_slide(find_layout_by_name(prs, m["toc"]))
    fill_placeholders(toc, ["目录", "背景\n方案\n计划"])

    section = prs.slides.add_slide(find_layout_by_name(prs, m["section"]))
    fill_placeholders(section, ["第一部分 - Overview", "这一节介绍核心内容", "01"])

    content = prs.slides.add_slide(find_layout_by_name(prs, m["content_with_subtitle"]))
    fill_placeholders(content, ["内容页示例", "This page reuses template style directly.", "副标题 - Subtitle"])

    end = prs.slides.add_slide(find_layout_by_name(prs, m["end"]))
    fill_placeholders(end, ["Thanks."])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output_path))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate PPT by reusing a corporate template.")
    parser.add_argument("--template", required=True, help="Path to template .pptx")
    parser.add_argument("--output", required=True, help="Path to output .pptx")
    parser.add_argument("--kb", default="template_knowledge_base.json", help="Path to output knowledge base json")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    template_path = Path(args.template)
    output_path = Path(args.output)
    kb_path = Path(args.kb)
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")
    kb = build_knowledge_base(template_path, kb_path)
    generate_demo(template_path, output_path, kb)
    print(f"Generated: {output_path.resolve()}")
    print(f"Knowledge base: {kb_path.resolve()}")


if __name__ == "__main__":
    main()
