from __future__ import annotations

import argparse
import asyncio
from pathlib import Path
from typing import Any

from pptx import Presentation


def _find_layout_by_name(prs: Presentation, keyword: str):
    for layout in prs.slide_layouts:
        if keyword in layout.name:
            return layout
    raise ValueError(f"Layout not found with keyword: {keyword}")


def _clear_all_slides(prs: Presentation) -> None:
    sld_id_lst = prs.slides._sldIdLst
    for sld_id in list(sld_id_lst):
        rel_id = sld_id.rId
        prs.part.drop_rel(rel_id)
        sld_id_lst.remove(sld_id)


def _fill_placeholders(slide, texts: list[str]) -> None:
    placeholders = []
    for shape in slide.shapes:
        if not getattr(shape, "is_placeholder", False):
            continue
        if not getattr(shape, "has_text_frame", False):
            continue
        idx = shape.placeholder_format.idx
        placeholders.append((idx, shape))
    placeholders.sort(key=lambda item: item[0])
    for i, text in enumerate(texts):
        if i >= len(placeholders):
            break
        placeholders[i][1].text = text


def _retain_slide_indices(prs: Presentation, keep_indices: set[int]) -> None:
    sld_id_lst = prs.slides._sldIdLst
    for idx in range(len(prs.slides) - 1, -1, -1):
        if idx in keep_indices:
            continue
        sld_id = sld_id_lst[idx]
        rel_id = sld_id.rId
        prs.part.drop_rel(rel_id)
        del sld_id_lst[idx]


def _build_examples_from_template(template_path: Path, output_path: Path) -> int:
    prs = Presentation(str(template_path))
    # 0: cover, 1: toc, 2: section, 3: content, 21: chart sample, 55: end
    keep = {0, 1, 2, 3, 21, 55}
    _retain_slide_indices(prs, keep)
    prs.save(str(output_path))
    return len(prs.slides)


async def handler(input: dict[str, Any], context: Any) -> dict[str, Any]:
    skill_root = Path(__file__).resolve().parent.parent
    template_file = input.get("template_file") or "PPT_Template.pptx"
    template_path = skill_root / template_file
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    mode = input.get("mode", "basic")
    title = input.get("title", "Demo Deck")
    toc_items = input.get("toc_items", ["Background", "Solution", "Plan"])
    section_title = input.get("section_title", "Section - Overview")
    content_title = input.get("content_title", "Content")
    content_body = input.get("content_body", "This slide is generated with template reuse.")
    output_filename = input.get("output_filename", "openclaw_generated.pptx")
    output_path = skill_root / output_filename

    if mode == "examples":
        slide_count = _build_examples_from_template(template_path, output_path)
        return {
            "output_path": str(output_path.resolve()),
            "slide_count": slide_count,
            "message": "Example slides generated from template sample pages",
        }

    prs = Presentation(str(template_path))
    _clear_all_slides(prs)

    cover = prs.slides.add_slide(_find_layout_by_name(prs, "封面_Cover"))
    _fill_placeholders(cover, [title, "Generated by OpenClaw skill"])

    toc = prs.slides.add_slide(_find_layout_by_name(prs, "目录页_Content"))
    _fill_placeholders(toc, ["目录", "\n".join(toc_items)])

    section = prs.slides.add_slide(_find_layout_by_name(prs, "章节页_Section page"))
    _fill_placeholders(section, [section_title, "Section summary", "01"])

    content = prs.slides.add_slide(_find_layout_by_name(prs, "标准内容页（小标题）_Standard page with subtitle"))
    _fill_placeholders(content, [content_title, content_body, "Subtitle"])

    end = prs.slides.add_slide(_find_layout_by_name(prs, "封底_End page"))
    _fill_placeholders(end, ["Thanks."])

    prs.save(str(output_path))

    return {
        "output_path": str(output_path.resolve()),
        "slide_count": len(prs.slides),
        "message": "PPT generated successfully",
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run ppt-template-builder locally.")
    parser.add_argument("--mode", default="basic", choices=["basic", "examples"])
    parser.add_argument("--title", default="Demo Deck")
    parser.add_argument("--output", default="openclaw_generated.pptx")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    payload = {
        "mode": args.mode,
        "title": args.title,
        "output_filename": args.output,
    }
    result = asyncio.run(handler(payload, None))
    print(result)


if __name__ == "__main__":
    main()
